#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSourceAutobot")]
	public partial class DataSourceAutobotDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataSourceAutobotDataContext() : 
				base(global::DataSource.Properties.Settings.Default.DataSourceAutobotConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceAutobotDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceAutobotDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceAutobotDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceAutobotDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AutobotDataSource> AutobotDataSources
		{
			get
			{
				return this.GetTable<AutobotDataSource>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutobotDataSource")]
	public partial class AutobotDataSource
	{
		
		private string _Id;
		
		private string _Indexes;
		
		private string _Action;
		
		private System.Nullable<System.DateTime> _ActionDates;
		
		public AutobotDataSource()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indexes", DbType="VarChar(MAX)")]
		public string Indexes
		{
			get
			{
				return this._Indexes;
			}
			set
			{
				if ((this._Indexes != value))
				{
					this._Indexes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(MAX)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this._Action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDates", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActionDates
		{
			get
			{
				return this._ActionDates;
			}
			set
			{
				if ((this._ActionDates != value))
				{
					this._ActionDates = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
